frameworkVersion: "3"
service: dans-website
provider:
  name: aws
  apiGateway:
    usagePlan:
      throttle:
        burstLimit: 200
        rateLimit: 100
    apiKeys:
      - ${self:provider.stage}-apiKey
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  profile: personal
  memorySize: 512
  timeout: 10
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
          Resource: 
            - '*'
  region: ca-central-1
  environment:
    # All variables in .env are automatically imported
functions:
  notifyByEmail:
    handler: notifyByEmail.lambda
    events:
      - http:
          path: contact
          method: post
          private: true
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  serverless-offline:
    port: 3000
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
    packager: yarn