const {
  NAV_LOGO,
  NAV_MENU,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB
} = require('.')

module.exports = {
  pageName: '#about',
  ABOUT_WINDOW: '#about-window',
  NAV_LOGO,
  NAV_MENU,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB
}
