const {
  NAV_LOGO,
  NAV_MENU,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB,
  COPYRIGHT_GITHUB_LINK
} = require('.')

module.exports = {
  pageName: '#contact',
  CONTACT_WINDOW: '#contact-window',
  CONTACT_TAB: '#contact-link',
  EMAIL_FORM: '#email-form',
  NAV_LOGO,
  NAV_MENU,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB,
  COPYRIGHT_GITHUB_LINK
}
