const {
  NAV_LOGO,
  NAV_MENU,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB,
  COPYRIGHT_GITHUB_LINK
} = require('.')

module.exports = {
  pageName: '#experience',
  EXPERIENCE_WINDOW: '#experience-window',
  EXPERIENCE_CARD: '#experience-card',
  NAV_LOGO,
  NAV_MENU,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB,
  COPYRIGHT_GITHUB_LINK
}
