const {
  NAV_MENU,
  NAV_LOGO,
  PAGE_TABS,
  TAB_ITEM,
  NAV,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB,
  PROJECTS_NAV_TAB,
  STICKY_GIF,
  COPYRIGHT_GITHUB_LINK
} = require('.')

module.exports = {
  pageName: '#landing',
  HERO_WINDOW: '#hero-window',
  ABOUT_LINK: '#about-link',
  CONTACT_LINK: '#contact-link',
  RESUME_LINK: '#resume-link',
  TYPEWRITER_TEXT: '#typewriter',
  NAV,
  NAV_LOGO,
  NAV_MENU,
  PAGE_TABS,
  TAB_ITEM,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB,
  PROJECTS_NAV_TAB,
  STICKY_GIF,
  COPYRIGHT_GITHUB_LINK
}
