const {
  NAV_MENU,
  NAV_LOGO,
  PAGE_TABS,
  TAB_ITEM,
  NAV,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB,
  STICKY_GIF
} = require('.')

module.exports = {
  pageName: '#landing',
  HERO_WINDOW: '#hero-window',
  NAV,
  NAV_LOGO,
  NAV_MENU,
  PAGE_TABS,
  TAB_ITEM,
  PAGE_MARQUEE,
  ABOUT_NAV_TAB,
  SPECIALITIES_NAV_TAB,
  EXPERIENCE_NAV_TAB,
  CONTACT_NAV_TAB,
  STICKY_GIF
}
